### ISSUE TITLE
[BUG] Permasigner executes w no errors but fails to create deb IOS

### ISSUE THREAD

**Issue by FreQRiDeR** [permasigner/permasigner#83]
**Describe the bug**
Python3 -m permasigner -p /path/to/***.ipa executes with no errors but fails to create deb in IOS. Python3 main.py -p command produces deb as expected.
**To reproduce**

1. Run '...'
2. Try and sign '...'
3. See error

**Expected behavior**

**Log**
Use the `--debug` option while running the script, and paste the output **into the codeblocks**.

```

```

**Which way are you running the script?**
ex. macOS 13.0, Windows with Docker, iOS 14.7.1
Ios 14.8 OddesseyRa1n
**Additional context**
Add any other context about the problem here (ex. can you identify the location in the source code where the problem exists, any possible solutions).

**Checklist**

-   [ ] All questions were answered if possible.
-   [ x] Bug was reproduced atleast 2 times.
-   [ x] You are using the latest version of the script (`git pull`).

**Comment by superrnovae** [comment]
Have you checked in ~/.permasigner/output ?

**Comment by FreQRiDeR** [comment]
Also, what is purpose of installing permasigner executable when you are still running it as a python script? ./permasigner prompts for L/I path but also fails to create deb.

**Comment by superrnovae** [comment]
> Also, what is purpose of installing permasigner executable when you are still running it as a python script? ./permasigner prompts for L/I path but also fails to create deb.

That’s not how it works. The executable does the same thing `python3 -m` does which is run the module as a script. 

You haven’t answered my question. Have you checked in /var/mobile/.permasigner/output ? 

When you run module as a script it will output to /var/mobile/.permasigner/output

You haven’t provided any logs. I’m not going to guess where the issue might be.

**Comment by FreQRiDeR** [comment]
Yes, they are in ~.permasigner/output. Why you would choose to put them in a hidden folder is beyond me but whatever. I can't keep up with all the changes you guys constantly make.

**Comment by superrnovae** [comment]
> Yes, they are in ~.permasigner/output. Why you would choose to put them in a hidden folder is beyond me but whatever. I can't keep up with all the changes you guys constantly make.

Had you provided the logs, you'd see that it's tells you where the output is.
Because you're running the module as a script for whatever reason. When you're in permasigner directory simply run it as `python3 main.py`. 

`python3 -m` is meant to be used when you're running from a package. 

There's also `-o` flag where you can override the output directory.

**Comment by FreQRiDeR** [comment]
Very well, thanks

**Comment by superrnovae** [comment]
[c98ae81f](https://github.com/permasigner/permasigner/commit/c98ae81f3d49ea8ce13d47c47a74962ab6612f5a) Permasigner will now always output in current working directory when run in a git repository or a tarball.

**Comment by FreQRiDeR** [comment]
No output in ApplicationSupport/premasigner/output

**Comment by superrnovae** [comment]
provide logs.
