### ISSUE TITLE
Quote prompt after latest pull, Update.

### ISSUE THREAD

**Issue by FreQRiDeR** [permasigner/permasigner#86]
Did latest pull, notices requirements update so installed them. Now I get a 'quote' response when running script. 

Last login: Thu Sep  8 15:07:21 on ttys001
terramoda@Mac-DaDDY ~ % cd permasigner         
terramoda@Mac-DaDDY permasigner % python3 -m permasigner -p /Volumes/HD DUE/Bk~Ups/IPA's/Taurine-1.1.6.ipa
quote> 

Bug? Fix? New Feature?

**Comment by itsnebulalol** [comment]
Could you try the pip package and see if the issue persists? If so, could you try a different path that isn’t in the folder with the ~ character?

**Comment by FreQRiDeR** [comment]
Ha, it was the ~ I believe. Seems to work fine now when using a different path, Thanks! :)

**Comment by superrnovae** [comment]
It was the single quote in `IPA's`

**Comment by itsnebulalol** [comment]
Oh, I didn’t even notice that
